spring:
  application:
    name: board
  profiles:
    active: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: "jdbc:mariadb://localhost:3306/board_db"
    username: board_user
    password: 1234

server:
  port: 8080